apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-data-pvc
  namespace: devops
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "default-nfs"
  resources:
    requests:
      storage: 100Gi
