apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarqube-data
  namespace: devops
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "default-nfs"
  resources:
    requests:
      storage: 10Gi
