apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-postgre-data
  namespace: devops
spec:
  storageClassName: "default-nfs"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

