apiVersion: v1
kind: Service
metadata:
  name: gitlab-postgre
  namespace: devops
  labels:
    app: gitlab-postgre
spec:
  type: NodePort
  ports:
  - port: 5432
    targetPort: 5432
    nodePort: 31433
    protocol: TCP
  selector:
    app: gitlab-postgre

