apiVersion: v1
kind: Service
metadata:
  name: gitlab-redis
  namespace: devops
  labels:
    name: gitlab-redis
spec:
  ports:
    - name: redis
      port: 16379
      targetPort: 6379
  selector:
    name: gitlab-redis
